package com.SmartLaundry.model;

public enum OrderStatus {
    PENDING,
    PENDING_FOR_PAYMENT,
    PICKED_UP,
    IN_CLEANING,
    READY_FOR_DELIVERY,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    ACCEPTED_BY_PROVIDER,
    COMPLETED,
    REJECTED_BY_PROVIDER,
    ACCEPTED_BY_AGENT,
    REJECTED_BY_AGENT,
    RESCHEDULED,
}

